name: map_tracker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  dropdown_button2: ^1.5.2
  elementary: ^1.3.1
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_archive: ^4.2.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.14.0
  flutter_svg: ^1.0.3
  freezed: ^1.1.0
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0
  logger: ^1.1.0
  path_provider: ^2.0.10
  provider: ^6.0.3
  retrofit: ^3.0.1+1
  sliding_up_panel: ^2.0.0+1
  surf_logger: ^1.0.2
  xml: 5.3.1

dev_dependencies:
  build_runner: ^2.1.10
  dart_code_metrics: ^4.14.0
  elementary_test: ^1.1.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.6
  isar_generator: ^2.5.0
  retrofit_generator: ^4.0.1
  surf_lint_rules: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
